"""Route contracts, discovery, registration, and built-in web routes."""

from wevra.web.routes.builtins import (
    build_wevra_web_module_routes,
    module_routes,
)
from wevra.web.routes.contracts import (
    API_PATH_PREFIX,
    PARTIAL_PATH_PREFIX,
    _normalise_path_prefix,
)
from wevra.web.routes.discovery import (
    CONTEXT_SURFACE_MODULE,
    ROUTE_EXPORT_ATTRIBUTE,
    ROUTE_SURFACE_MODULE,
    STATIC_RESOURCE_DIRECTORY,
    TEMPLATE_RESOURCE_DIRECTORY,
    ModuleSurface,
    context_providers_from_modules,
    discover_context_providers,
    discover_module_routes,
    discover_module_surface,
    discover_module_surfaces,
    discover_static_sources,
    discover_template_sources,
    static_sources_from_modules,
    template_sources_from_modules,
)
from wevra.web.routes.registration import (
    ConfiguredRouteSettings,
    HtmlRouteDefinition,
    HtmlSurface,
    HtmlView,
    ModuleRoutes,
    RouteCompositionError,
    compose_module_routes,
    load_configured_module_routes,
    load_module_routes,
    merge_module_routes,
    register_configured_module_routes,
    register_module_routes,
    route_prefixes_from_app_config,
)

__all__ = [
    "API_PATH_PREFIX",
    "CONTEXT_SURFACE_MODULE",
    "ConfiguredRouteSettings",
    "HtmlRouteDefinition",
    "HtmlSurface",
    "HtmlView",
    "ModuleRoutes",
    "ModuleSurface",
    "PARTIAL_PATH_PREFIX",
    "ROUTE_EXPORT_ATTRIBUTE",
    "ROUTE_SURFACE_MODULE",
    "RouteCompositionError",
    "STATIC_RESOURCE_DIRECTORY",
    "TEMPLATE_RESOURCE_DIRECTORY",
    "_normalise_path_prefix",
    "build_wevra_web_module_routes",
    "compose_module_routes",
    "context_providers_from_modules",
    "discover_context_providers",
    "discover_module_routes",
    "discover_module_surface",
    "discover_module_surfaces",
    "discover_static_sources",
    "discover_template_sources",
    "load_configured_module_routes",
    "load_module_routes",
    "merge_module_routes",
    "module_routes",
    "register_configured_module_routes",
    "register_module_routes",
    "route_prefixes_from_app_config",
    "static_sources_from_modules",
    "template_sources_from_modules",
]
