"""Core route discovery, registration, metadata, and inspection support."""

from wybra.core.routes.contracts import (
    API_PATH_PREFIX,
    PARTIAL_PATH_PREFIX,
    _normalise_path_prefix,
)
from wybra.core.routes.discovery import (
    ROUTE_EXPORT_ATTRIBUTE,
    ROUTE_MODULE,
    ModuleSurface,
    discover_module_routers,
    discover_module_surface,
    discover_module_surfaces,
)
from wybra.core.routes.inspection import (
    ROUTE_METHODS_ATTRIBUTE,
    ROUTE_PATH_ATTRIBUTE,
    ROUTE_TEMPLATE_ATTRIBUTE,
    ROUTE_TYPE_ATTRIBUTE,
    EndpointShape,
    RouteInspection,
    RouteKind,
    RouteOrigin,
    RouteProblem,
    RouteProblemKind,
    RouteRecord,
    RouteTreeNode,
    RouteType,
    inspect_route_tree,
    record_route_origin,
    route,
    route_template,
    route_type,
)
from wybra.core.routes.registration import (
    ConfiguredModuleRouter,
    ConfiguredRouteSettings,
    ModuleRouters,
    RouteCompositionError,
    load_configured_module_routes,
    load_module_routes,
    register_configured_module_routes,
    register_module_routes,
    route_prefixes_from_app_config,
    route_prefixes_from_settings,
)
from wybra.core.routes.setup import register_configured_routes_for_site
from wybra.core.routes.validation import validate_routes

__all__ = [
    "API_PATH_PREFIX",
    "ConfiguredModuleRouter",
    "ConfiguredRouteSettings",
    "EndpointShape",
    "ModuleRouters",
    "ModuleSurface",
    "PARTIAL_PATH_PREFIX",
    "ROUTE_EXPORT_ATTRIBUTE",
    "ROUTE_METHODS_ATTRIBUTE",
    "ROUTE_MODULE",
    "ROUTE_PATH_ATTRIBUTE",
    "ROUTE_TEMPLATE_ATTRIBUTE",
    "ROUTE_TYPE_ATTRIBUTE",
    "RouteCompositionError",
    "RouteInspection",
    "RouteKind",
    "RouteOrigin",
    "RouteProblem",
    "RouteProblemKind",
    "RouteRecord",
    "RouteTreeNode",
    "RouteType",
    "_normalise_path_prefix",
    "discover_module_routers",
    "discover_module_surface",
    "discover_module_surfaces",
    "inspect_route_tree",
    "load_configured_module_routes",
    "load_module_routes",
    "record_route_origin",
    "register_configured_module_routes",
    "register_configured_routes_for_site",
    "register_module_routes",
    "route",
    "route_template",
    "route_prefixes_from_app_config",
    "route_prefixes_from_settings",
    "route_type",
    "validate_routes",
]
