"""Route contracts, discovery, registration, and built-in web routes."""

from wybra.web.routes.builtins import module_routers
from wybra.web.routes.contracts import (
    API_PATH_PREFIX,
    PARTIAL_PATH_PREFIX,
    _normalise_path_prefix,
)
from wybra.web.routes.discovery import (
    ROUTE_EXPORT_ATTRIBUTE,
    ROUTE_SURFACE_MODULE,
    ModuleSurface,
    discover_module_routers,
    discover_module_surface,
    discover_module_surfaces,
)
from wybra.web.routes.inspection import (
    EndpointShape,
    RouteInspection,
    RouteKind,
    RouteOrigin,
    RouteProblem,
    RouteProblemKind,
    RouteRecord,
    RouteSurface,
    RouteTreeNode,
    inspect_route_tree,
    record_route_origin,
    render_graph,
    render_json,
    render_mermaid,
    render_succinct,
    route_surface,
)
from wybra.web.routes.registration import (
    ConfiguredModuleRouter,
    ConfiguredRouteSettings,
    ModuleRouters,
    RouteCompositionError,
    load_configured_module_routes,
    load_module_routes,
    register_configured_module_routes,
    register_module_routes,
    route_prefixes_from_app_config,
    route_prefixes_from_settings,
)

__all__ = [
    "API_PATH_PREFIX",
    "ConfiguredModuleRouter",
    "ConfiguredRouteSettings",
    "EndpointShape",
    "ModuleRouters",
    "ModuleSurface",
    "PARTIAL_PATH_PREFIX",
    "ROUTE_EXPORT_ATTRIBUTE",
    "ROUTE_SURFACE_MODULE",
    "RouteInspection",
    "RouteKind",
    "RouteOrigin",
    "RouteProblem",
    "RouteProblemKind",
    "RouteCompositionError",
    "RouteRecord",
    "RouteSurface",
    "RouteTreeNode",
    "_normalise_path_prefix",
    "discover_module_routers",
    "discover_module_surface",
    "discover_module_surfaces",
    "inspect_route_tree",
    "load_configured_module_routes",
    "load_module_routes",
    "module_routers",
    "record_route_origin",
    "register_configured_module_routes",
    "register_module_routes",
    "render_graph",
    "render_json",
    "render_mermaid",
    "render_succinct",
    "route_prefixes_from_app_config",
    "route_prefixes_from_settings",
    "route_surface",
]
