"""Public form and CSRF capability API."""

from __future__ import annotations

from importlib import import_module
from typing import Any

_EXPORT_MODULES = {
    "CSRF_COOKIE_NAME": "wybra.forms.csrf",
    "CSRF_EXEMPT_ENDPOINT_ATTR": "wybra.forms.csrf",
    "CSRF_FIELD_NAME": "wybra.forms.csrf",
    "CSRF_FORM_DATA_STATE_ATTR": "wybra.forms.csrf",
    "CSRF_HEADER_NAME": "wybra.forms.csrf",
    "CSRF_RESPONSE_FINALISATION_STATE_ATTR": "wybra.forms.csrf",
    "CSRF_TOKEN_MAX_AGE_SECONDS": "wybra.forms.csrf",
    "CsrfProtector": "wybra.forms.csrf",
    "Attr": "wybra.forms.model_forms",
    "Binding": "wybra.forms.model_forms",
    "CheckboxField": "wybra.forms.fields",
    "ChoiceField": "wybra.forms.fields",
    "CountryChoice": "wybra.forms.phone_contact",
    "CountryFilter": "wybra.forms.phone_contact",
    "DateField": "wybra.forms.fields",
    "DateTimeField": "wybra.forms.fields",
    "DefaultFormsCapability": "wybra.forms.capabilities",
    "CSRF_TOKEN_SECRET_KEY_CURRENT": "wybra.forms.config",
    "CSRF_TOKEN_SECRET_KEY_PREVIOUS": "wybra.forms.config",
    "Field": "wybra.forms.fields",
    "FieldHandler": "wybra.forms.phone_contact",
    "FieldResult": "wybra.forms.fields",
    "FileUploadField": "wybra.forms.fields",
    "FORMS_CONFIG_SECTION": "wybra.forms.config",
    "Form": "wybra.forms.fields",
    "FormError": "wybra.forms.fields",
    "FormResult": "wybra.forms.fields",
    "FormsCapability": "wybra.forms.capabilities",
    "FormsSettings": "wybra.forms.settings",
    "HiddenField": "wybra.forms.fields",
    "JsonPath": "wybra.forms.model_forms",
    "ModelBindingError": "wybra.forms.model_forms",
    "ModelForm": "wybra.forms.model_forms",
    "ModelFormDeclarationError": "wybra.forms.model_forms",
    "ModelFormError": "wybra.forms.model_forms",
    "MultiSelectField": "wybra.forms.fields",
    "Option": "wybra.forms.fields",
    "NormalisedPhoneContact": "wybra.forms.phone_contact",
    "PhoneContactControl": "wybra.forms.phone_contact",
    "PhoneContactError": "wybra.forms.phone_contact",
    "PhoneContactValidation": "wybra.forms.phone_contact",
    "PhoneContactWidgetError": "wybra.forms.phone_contact_rendering",
    "PositiveIntegerField": "wybra.forms.fields",
    "RadioField": "wybra.forms.fields",
    "ReadOnly": "wybra.forms.model_forms",
    "SelectField": "wybra.forms.fields",
    "SliderField": "wybra.forms.fields",
    "SubdivisionChoice": "wybra.forms.phone_contact",
    "SubdivisionFilter": "wybra.forms.phone_contact",
    "SwitchField": "wybra.forms.fields",
    "TemplateFormRenderer": "wybra.forms.rendering",
    "TextAreaField": "wybra.forms.fields",
    "TextField": "wybra.forms.fields",
    "TimeField": "wybra.forms.fields",
    "UnknownFormFieldError": "wybra.forms.fields",
    "UnknownInitialFieldError": "wybra.forms.fields",
    "UnknownWidgetError": "wybra.forms.rendering",
    "csrf_exempt": "wybra.forms.csrf",
    "csrf_response_finalisation_requested": "wybra.forms.csrf",
    "country_choices": "wybra.forms.phone_contact",
    "country_flag": "wybra.forms.phone_contact",
    "dial_prefix": "wybra.forms.phone_contact",
    "field_handler": "wybra.forms.phone_contact",
    "form_control": "wybra.forms.phone_contact",
    "forms_rendering_context": "wybra.forms.rendering",
    "forms_provider_configured": "wybra.forms.capabilities",
    "is_form_content_type": "wybra.forms.security",
    "is_safe_method": "wybra.forms.security",
    "module_config": "wybra.forms.config",
    "normalise_content_type": "wybra.forms.security",
    "normalise_phone_contact": "wybra.forms.phone_contact",
    "phone_number_type_name": "wybra.forms.phone_contact",
    "request_csrf_response_finalisation": "wybra.forms.csrf",
    "request_form_data": "wybra.forms.csrf",
    "render_csrf_field": "wybra.forms.rendering",
    "render_field": "wybra.forms.rendering",
    "render_form": "wybra.forms.rendering",
    "render_phone_contact": "wybra.forms.rendering",
    "render_phone_contact_fields": "wybra.forms.rendering",
    "register_phone_contact_field_handlers": "wybra.forms.phone_contact",
    "setup_site": "wybra.forms.setup",
    "subdivision_choices": "wybra.forms.phone_contact",
    "validate_csrf": "wybra.forms.csrf",
    "validate_forms": "wybra.forms.validation",
    "validation_targets": "wybra.forms.validation",
}

provides_forms_capability = True


def __getattr__(name: str) -> Any:
    module_name = _EXPORT_MODULES.get(name)
    if module_name is None:
        raise AttributeError(f"module 'wybra.forms' has no attribute {name!r}")
    value = getattr(import_module(module_name), name)
    globals()[name] = value
    return value


__all__ = [
    "CSRF_COOKIE_NAME",
    "CSRF_EXEMPT_ENDPOINT_ATTR",
    "CSRF_FIELD_NAME",
    "CSRF_FORM_DATA_STATE_ATTR",
    "CSRF_HEADER_NAME",
    "CSRF_RESPONSE_FINALISATION_STATE_ATTR",
    "CSRF_TOKEN_MAX_AGE_SECONDS",
    "CsrfProtector",
    "Attr",
    "Binding",
    "CheckboxField",
    "ChoiceField",
    "CountryChoice",
    "CountryFilter",
    "DateField",
    "DateTimeField",
    "DefaultFormsCapability",
    "CSRF_TOKEN_SECRET_KEY_CURRENT",
    "CSRF_TOKEN_SECRET_KEY_PREVIOUS",
    "Field",
    "FieldHandler",
    "FieldResult",
    "FileUploadField",
    "FORMS_CONFIG_SECTION",
    "Form",
    "FormError",
    "FormResult",
    "FormsCapability",
    "FormsSettings",
    "HiddenField",
    "JsonPath",
    "ModelBindingError",
    "ModelForm",
    "ModelFormDeclarationError",
    "ModelFormError",
    "MultiSelectField",
    "Option",
    "NormalisedPhoneContact",
    "PhoneContactControl",
    "PhoneContactError",
    "PhoneContactValidation",
    "PhoneContactWidgetError",
    "PositiveIntegerField",
    "RadioField",
    "ReadOnly",
    "SelectField",
    "SliderField",
    "SubdivisionChoice",
    "SubdivisionFilter",
    "SwitchField",
    "TemplateFormRenderer",
    "TextAreaField",
    "TextField",
    "TimeField",
    "UnknownFormFieldError",
    "UnknownInitialFieldError",
    "UnknownWidgetError",
    "csrf_exempt",
    "csrf_response_finalisation_requested",
    "country_choices",
    "country_flag",
    "dial_prefix",
    "field_handler",
    "form_control",
    "forms_rendering_context",
    "forms_provider_configured",
    "is_form_content_type",
    "is_safe_method",
    "module_config",
    "normalise_content_type",
    "normalise_phone_contact",
    "phone_number_type_name",
    "provides_forms_capability",
    "request_csrf_response_finalisation",
    "request_form_data",
    "render_csrf_field",
    "render_field",
    "render_form",
    "render_phone_contact",
    "render_phone_contact_fields",
    "register_phone_contact_field_handlers",
    "setup_site",
    "subdivision_choices",
    "validate_csrf",
    "validate_forms",
    "validation_targets",
]
