"""Public form and CSRF capability API."""

from __future__ import annotations

from importlib import import_module
from typing import Any

_EXPORT_MODULES = {
    "CSRF_COOKIE_NAME": "wybra.forms.csrf",
    "CSRF_EXEMPT_ENDPOINT_ATTR": "wybra.forms.csrf",
    "CSRF_FIELD_NAME": "wybra.forms.csrf",
    "CSRF_FORM_DATA_STATE_ATTR": "wybra.forms.csrf",
    "CSRF_HEADER_NAME": "wybra.forms.csrf",
    "CSRF_RESPONSE_FINALISATION_STATE_ATTR": "wybra.forms.csrf",
    "CsrfProtector": "wybra.forms.csrf",
    "CheckboxField": "wybra.forms.fields",
    "ChoiceField": "wybra.forms.fields",
    "DateField": "wybra.forms.fields",
    "DateTimeField": "wybra.forms.fields",
    "DefaultFormsCapability": "wybra.forms.capabilities",
    "Field": "wybra.forms.fields",
    "FieldResult": "wybra.forms.fields",
    "FORMS_CONFIG_SECTION": "wybra.forms.config",
    "Form": "wybra.forms.fields",
    "FormError": "wybra.forms.fields",
    "FormResult": "wybra.forms.fields",
    "FormsCapability": "wybra.forms.capabilities",
    "FormsSettings": "wybra.forms.settings",
    "GENERATE_LOCAL_CSRF_SECRET": "wybra.forms.config",
    "HiddenField": "wybra.forms.fields",
    "MultiSelectField": "wybra.forms.fields",
    "Option": "wybra.forms.fields",
    "PositiveIntegerField": "wybra.forms.fields",
    "RadioField": "wybra.forms.fields",
    "SelectField": "wybra.forms.fields",
    "SliderField": "wybra.forms.fields",
    "SwitchField": "wybra.forms.fields",
    "TemplateFormRenderer": "wybra.forms.rendering",
    "TextAreaField": "wybra.forms.fields",
    "TextField": "wybra.forms.fields",
    "TimeField": "wybra.forms.fields",
    "UnknownFormFieldError": "wybra.forms.fields",
    "UnknownInitialFieldError": "wybra.forms.fields",
    "UnknownWidgetError": "wybra.forms.rendering",
    "csrf_exempt": "wybra.forms.csrf",
    "csrf_response_finalisation_requested": "wybra.forms.csrf",
    "forms_rendering_context": "wybra.forms.rendering",
    "forms_provider_configured": "wybra.forms.capabilities",
    "is_form_content_type": "wybra.forms.security",
    "is_safe_method": "wybra.forms.security",
    "module_config": "wybra.forms.config",
    "normalise_content_type": "wybra.forms.security",
    "request_csrf_response_finalisation": "wybra.forms.csrf",
    "request_form_data": "wybra.forms.csrf",
    "render_csrf_field": "wybra.forms.rendering",
    "render_field": "wybra.forms.rendering",
    "render_form": "wybra.forms.rendering",
    "setup_site": "wybra.forms.setup",
    "validate_csrf": "wybra.forms.csrf",
    "validate_forms": "wybra.forms.validation",
    "validation_targets": "wybra.forms.validation",
}

provides_forms_capability = True


def __getattr__(name: str) -> Any:
    module_name = _EXPORT_MODULES.get(name)
    if module_name is None:
        raise AttributeError(f"module 'wybra.forms' has no attribute {name!r}")
    value = getattr(import_module(module_name), name)
    globals()[name] = value
    return value


__all__ = [
    "CSRF_COOKIE_NAME",
    "CSRF_EXEMPT_ENDPOINT_ATTR",
    "CSRF_FIELD_NAME",
    "CSRF_FORM_DATA_STATE_ATTR",
    "CSRF_HEADER_NAME",
    "CSRF_RESPONSE_FINALISATION_STATE_ATTR",
    "CsrfProtector",
    "CheckboxField",
    "ChoiceField",
    "DateField",
    "DateTimeField",
    "DefaultFormsCapability",
    "Field",
    "FieldResult",
    "FORMS_CONFIG_SECTION",
    "Form",
    "FormError",
    "FormResult",
    "FormsCapability",
    "FormsSettings",
    "GENERATE_LOCAL_CSRF_SECRET",
    "HiddenField",
    "MultiSelectField",
    "Option",
    "PositiveIntegerField",
    "RadioField",
    "SelectField",
    "SliderField",
    "SwitchField",
    "TemplateFormRenderer",
    "TextAreaField",
    "TextField",
    "TimeField",
    "UnknownFormFieldError",
    "UnknownInitialFieldError",
    "UnknownWidgetError",
    "csrf_exempt",
    "csrf_response_finalisation_requested",
    "forms_rendering_context",
    "forms_provider_configured",
    "is_form_content_type",
    "is_safe_method",
    "module_config",
    "normalise_content_type",
    "provides_forms_capability",
    "request_csrf_response_finalisation",
    "request_form_data",
    "render_csrf_field",
    "render_field",
    "render_form",
    "setup_site",
    "validate_csrf",
    "validate_forms",
    "validation_targets",
]
