"""Render nginx configuration for externally served static asset CORS."""

from __future__ import annotations

from wybra.security.cors import CorsPolicy, CorsPolicySet


def render_nginx_cors_config(policy_set: CorsPolicySet) -> str:
    lines = [
        "# Generated by wybra-collect --nginx-cors.",
        "# Include this section inside the nginx server block that serves assets.",
    ]
    if policy_set.enabled:
        lines.extend(_location_block("/", policy_set))
    for path, policy in sorted(policy_set.paths.items()):
        lines.extend(_location_block(path, policy))
    return "\n".join(lines) + "\n"


def _location_block(path: str, policy: CorsPolicy) -> list[str]:
    location = "/" if path == "/" else path.rstrip("/")
    location_path = "/" if location == "/" else f"{location}/"
    lines = [f"location {location_path} {{"]
    for header, value in _cors_headers(policy):
        lines.append(f"    add_header {header} {_nginx_quote(value)} always;")
    lines.append("}")
    return lines


def _cors_headers(policy: CorsPolicy) -> tuple[tuple[str, str], ...]:
    headers = [
        ("Access-Control-Allow-Origin", " ".join(policy.allow_origins)),
        ("Access-Control-Allow-Methods", ", ".join(policy.allow_methods)),
        ("Access-Control-Max-Age", str(policy.max_age)),
    ]
    if policy.allow_headers:
        headers.append(
            ("Access-Control-Allow-Headers", ", ".join(policy.allow_headers))
        )
    if policy.expose_headers:
        headers.append(
            ("Access-Control-Expose-Headers", ", ".join(policy.expose_headers))
        )
    if policy.allow_credentials:
        headers.append(("Access-Control-Allow-Credentials", "true"))
    return tuple(headers)


def _nginx_quote(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'
