"""Render nginx configuration for externally served static asset CORS."""

from __future__ import annotations

from wybra.security.cors import CorsPolicy, CorsPolicySet


def render_nginx_cors_config(policy_set: CorsPolicySet) -> str:
    lines = [
        "# Generated by wybra-collect --nginx-cors.",
        "# Include this section inside the nginx server block that serves assets.",
    ]
    if policy_set.enabled:
        lines.extend(_location_block("/", policy_set))
    for path, policy in sorted(policy_set.paths.items()):
        lines.extend(_location_block(path, policy))
    return "\n".join(lines) + "\n"


def _location_block(path: str, policy: CorsPolicy) -> list[str]:
    location = "/" if path == "/" else path.rstrip("/")
    lines = [f"location {location}/ {{"]
    for header, value in _cors_headers(policy):
        lines.append(f"    add_header {header} {_nginx_quote(value)} always;")
    lines.append("}")
    return lines


def _cors_headers(policy: CorsPolicy) -> tuple[tuple[str, str], ...]:
    return (
        ("Access-Control-Allow-Origin", " ".join(policy.allow_origins)),
        ("Access-Control-Allow-Methods", ", ".join(policy.allow_methods)),
        ("Access-Control-Allow-Headers", ", ".join(policy.allow_headers)),
        ("Access-Control-Expose-Headers", ", ".join(policy.expose_headers)),
        (
            "Access-Control-Allow-Credentials",
            "true" if policy.allow_credentials else "false",
        ),
        ("Access-Control-Max-Age", str(policy.max_age)),
    )


def _nginx_quote(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'
